'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CarStudio.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property advanced() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("advanced", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aerial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aerial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property always() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("always", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property amateur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("amateur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Axle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Axle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Axle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Axle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Axle2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Axle2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BaseCarbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BaseCarbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property body() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("body", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bronze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bronze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cache() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cache", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Checkbox_checked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Checkbox_checked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property electrique() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("electrique", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Frontend() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frontend", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property glow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("glow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gradinv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gradinv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property launchrv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("launchrv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property never() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("never", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Panel_Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Panel_Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pin2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pin2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rookie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rookie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RVCS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RVCS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RVCS2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RVCS2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rvcs3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rvcs3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RVL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RVL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RVLB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RVLB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property semipro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("semipro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shadow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shadow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property silver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spring2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spring2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sprite1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sprite1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tex_active() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tex_active", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ufo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ufo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Wheel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wheel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property window_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
